### ISSUE TITLE
Unable to `make build` on either RHEL-9 or Alpine v3.18

### ISSUE THREAD

**Issue by james-stevens** [dmachard/go-dnscollector#499]
**Describe the bug**
```
[go-dnscollector]$ make build
CGO_ENABLED=0 go build -v -ldflags="-s -w  -X github.com/prometheus/common/version.Version=a4f4f3f -X github.com/prometheus/common/version.Revision=a4f4f3f -X github.com/prometheus/common/version.Branch=main -X github.com/prometheus/common/version.BuildDate=2023-12-05_16:53:02_+0000" -o go-dnscollector dnscollector.go
command-line-arguments
# command-line-arguments
./dnscollector.go:104:5: undefined: IsMuxEnabled
./dnscollector.go:106:3: undefined: InitMultiplexer
./dnscollector.go:130:8: undefined: IsMuxEnabled
./dnscollector.go:131:6: undefined: ReloadMultiplexer
make: *** [Makefile:42: build] Error 1
```

I get these four errors when I try & build on either RHEL-9 or Alpine v3.18 - I googled the messages but google found nothing.

Unfortunately I don't know anything about `go`, so don't really know how to take this any further.

**To Reproduce**
on Alpine v3.18 or RHEL-9, run `make build`

**Expected behavior**
apparently `make build; make run` works

**Additional context**
Using latest `master` branch, cos we're trying to add a new feature we need in the powerdns recursor protobuf parser.

**Comment by kabenin** [comment]
Hey @james-stevens , can you please try running `make` (not make build)?
The build target does not have a dependency on dep target, which installs a bunch of modules needed.

**Comment by james-stevens** [comment]
> Hey @james-stevens , can you please try running `make` (not make build)? The build target does not have a dependency on dep target, which installs a bunch of modules needed.

sure - no probs - your instructions said `make build; make run` :)

I'll try tomorrow - getting late here

**Comment by dmachard** [comment]
Hi, 

Could you please retry with the latest pull request that was merged into the main branch?
I added some tests to detect regression in the make file. It should be working fine now.

Keep in mind that the main branch may occasionally contain unstable code. I recommend using the provided [releases](https://github.com/dmachard/go-dnscollector/releases) or building from a specific tag for a more stable version.

Denis

**Comment by james-stevens** [comment]
The problem with trying to add features to an older version of the code is you can then end up with conflicts when try to get it merged back - hence I was going with `master`.

Using `make` has different issues.

```
[james.stevens@compile01 go-dnscollector]$ go version
go version go1.20.10 linux/amd64
[james.stevens@compile01 go-dnscollector]$ make
go: go.mod file indicates go 1.21, but maximum version supported by tidy is 1.20
make: *** [Makefile:39: dep] Error 1
```
This was after removing everything & recloning the latest `master` - I will try the most recent release.


The feature we want to add is a missing field in the PowerDNS recursor protobuf parser. `appliedPolicyType` is included as `AppliedPolicy` (aka `applied-policy`), but not `appliedPolicyTrigger`.

```
    optional PolicyType appliedPolicyType = 7;  // Type of the filtering policy (RPZ or Lua) applied
    optional string appliedPolicyTrigger = 8;   // The RPZ trigger
```
https://docs.powerdns.com/recursor/lua-config/protobuf.html

`appliedPolicyTrigger` says which rule in the `appliedPolicyType` was triggered to cause the RPZ event. As we have RPZs consisting of millions of records, including lots of wildcards, trying to reverse engineer which rule was hit is pretty much impossible and seems kinda pointless as PowerDNS recursor will tell you.

BTW: as a general rule, using a hyphen in a property name, as in `applied-policy`, can be kinda awkward for downstream processing when the record arrives as JSON & you want to parse it in various different environments. Using underscore as a name separator is generally more universally supported.

**Comment by dmachard** [comment]
> [james.stevens@compile01 go-dnscollector]$ go version
> go version go1.20.10 linux/amd64
> [james.stevens@compile01 go-dnscollector]$ make
> go: go.mod file indicates go 1.21, but maximum version supported by tidy is 1.20
> make: *** [Makefile:39: dep] Error 1
> ```

Could you update the var [`GO_VERSION := 1.21`](https://github.com/dmachard/go-dnscollector/blob/a64d849944fe902625e99bdad9f6a37956485ea2/Makefile#L3C1-L3C19) in the Makefile with 1.20 ?

**Comment by dmachard** [comment]
> The feature we want to add is a missing field in the PowerDNS recursor protobuf parser. `appliedPolicy` is included as `AppliedPolicy` (aka `applied-policy`), but not `appliedPolicyTrigger`.
> 
> ```
>     optional string appliedPolicy = 3;          // Filtering policy (RPZ or Lua) applied
>     repeated string tags = 4;                   // Additional tags applied
>     optional uint32 queryTimeSec = 5;           // Time of the corresponding query reception (seconds since epoch)
>     optional uint32 queryTimeUsec = 6;          // Time of the corresponding query reception (additional micro-seconds)
>     optional PolicyType appliedPolicyType = 7;  // Type of the filtering policy (RPZ or Lua) applied
>     optional string appliedPolicyTrigger = 8;   // The RPZ trigger
> ```
> 
> https://docs.powerdns.com/recursor/lua-config/protobuf.html
> 
> `appliedPolicyTrigger` says which rule in the `appliedPolicy` was triggered to cause the RPZ event. As we have RPZs consisting of millions of records, including lots of wildcards, trying to reverse engineer which rule was hit is pretty much impossible and seems kinda pointless as PowerDNS recursor will tell you.
> 
> BTW: as a general rule, using a hyphen in a property name, as in `applied-policy`, can be kinda awkward for downstream processing when the record arrives as JSON & you want to parse it in various different environments. Using underscore as a name separator is generally more universally supported.

Don't hesitate to track this feature in another issue.
This tool is always under active development so perhaps we can can make some adaptations in the model.

**Comment by dmachard** [comment]
A very fast way is to use the go command ’go run .’ at the top of the project, all dependancies will be downloaded according to your go version

A second way is to use the dockerfile to build it.

Finnally, you can use the makefile but go1.21 expected on your system

**Comment by james-stevens** [comment]
Editing the `Makefile`, then running `make` produced a binary that runs just fine, so looks like that worked.

`go run` just gives the message `go: no go files listed`

**Comment by dmachard** [comment]
Go run with . At the end
`go run .`

**Comment by dmachard** [comment]
Makefile has been improved with PR #502 to detect the go version in a dynamic way.

**Comment by dmachard** [comment]
Fixed in v0.39.0.
